name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    services:
      threads:
        image: textile/go-threads:latest
        env:
          THRDS_HOSTADDR: /ip4/0.0.0.0/tcp/4006
          THRDS_SERVICEAPIADDR: /ip4/0.0.0.0/tcp/5006
          THRDS_SERVICEAPIPROXYADDR: /ip4/0.0.0.0/tcp/5007
          THRDS_APIADDR: /ip4/0.0.0.0/tcp/6006
          THRDS_APIPROXYADDR: /ip4/0.0.0.0/tcp/6007
        ports:
        - 4006:4006
        - 5006:5006
        - 5007:5007
        - 6006:6006
        - 6007:6007
      peer:
        image: textile/go-threads:latest
        env:
          THRDS_HOSTADDR: /ip4/0.0.0.0/tcp/4007
          THRDS_SERVICEAPIADDR: /ip4/0.0.0.0/tcp/5008
          THRDS_SERVICEAPIPROXYADDR: /ip4/0.0.0.0/tcp/5009
          THRDS_APIADDR: /ip4/0.0.0.0/tcp/6008
          THRDS_APIPROXYADDR: /ip4/0.0.0.0/tcp/6009
        ports:
        - 4007:4007
        - 5008:5008
        - 5009:5009
        - 6008:6008
        - 6009:6009
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
            export PATH="$PATH:/usr/lib/dart/bin";
            pub get
    - name: Run tests
      run: |
           export PATH=/usr/lib/dart/bin:$PATH;
           sleep 5; pub run test
      env:
        THREADS_HOST: threads
        THREADS_PORT: ${{ job.services.threads.ports[6006] }}
        PEER_HOST: peer
        PEER_PORT: ${{ job.services.peer.ports[6008] }}
